### ISSUE TITLE
USBGuard Qt Applet: Show warning and error messages of daemon

### ISSUE THREAD

**Issue by genodeftest** [USBGuard/usbguard#118]
`systemctl status usbguard.service` shows these error and warning messages (caused by #112, #116 and #117 respectively):

```
warning: The configured rule file doesn't yet exists. Starting with an empty rule set.
warning: IPCException: NotFound: Requested action depends on a resource which is not available
error: Exception caught during device insertion processing: /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3: Invalid descriptor data: bLength doesn't match expected bLenght for this descriptor type
```

USBGuard Qt Applet doesn't show them in its "Messages" tab. This could probably be improved.

**Comment by dkopecek** [comment]
Closing this as I've removed the applet from the main usbguard repository in https://github.com/USBGuard/usbguard/commit/bf3bb09edf491892617d35b55edec06f92d2743f. The plan is to simplify it down to a minimal required use case and maintain it in a separate repository.
