### ISSUE TITLE
USBGuard on Ubuntu 16.04

### ISSUE THREAD

**Issue by MatejKovacic** [USBGuard/usbguard#145]
Hi,

I installed USB Guard on Ubuntu 16.04 system:

git clone https://github.com/dkopecek/usbguard
cd usbguard/
./autogen.sh

sudo apt install libgcrypt11-dev libsodium-dev protobuf-compiler libprotobuf-dev libdbus-1-dev libdbus-glib-1-dev libpolkit-gobject-1-dev

./configure --prefix=/usr --sysconfdir=/etc --with-bundled-catch --with-bundled-pegtl
make
sudo make install
sudo ldconfig

However, when I try to start it, it says:
sudo systemctl start usbguard.service

Failed to start usbguard.service: Unit usbguard.service not found.

Also, there is no GUI (or at least I am unable to find it)... Any help will be much appreciated.

**Comment by MatejKovacic** [comment]
Hi,

I already figured out how to do it. Here is a complete "receipt", you can use it on Wiki:
```
git clone https://github.com/dkopecek/usbguard
sudo apt install libgcrypt11-dev libsodium-dev protobuf-compiler libprotobuf-dev libdbus-1-dev libdbus-glib-1-dev libpolkit-gobject-1-dev
cd usbguard/
./autogen.sh
./configure --prefix=/usr --sysconfdir=/etc --with-bundled-catch --with-bundled-pegtl --with-gui-qt=qt4 --enable-systemd
make
sudo make install
sudo ldconfig

sudo usbguard generate-policy > rules.conf
sudo install -m 0600 -o root -g root rules.conf /etc/usbguard/rules.conf

sudo systemctl restart usbguard

usbguard-applet-qt
```

Works like a charm!

**Comment by dkopecek** [comment]
Hi, thanks for the receipt! I have one more enhancement. Don't not install both libsodium-dev and libgcrypt11-dev. You need only one of those. If you want gcrypt for example, use the --with-crypto-library=gcrypt and install just libgcrypt11-dev.

**Comment by fauno** [comment]
also missing `libqt4-dev libseccomp-dev xsltproc` :)

**Comment by subversive-owl** [comment]
Also, `sudo apt install libtool`

**Comment by fcsonline** [comment]
The `usbguard-applet-qt` was not working for me in `HEAD`. I just checked the last stable tag out before build it:

`git checkout usbguard-0.7.0`

**Comment by i8x4t** [comment]
I get the following error trying to run autogen.sh on Ubuntu 16.04 `configure.ac:97: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:155: error: possibly undefined macro: AC_DEFINE
configure.ac:166: error: possibly undefined macro: AC_MSG_FAILURE
configure.ac:236: error: possibly undefined macro: AC_MSG_NOTICE
configure.ac:252: error: possibly undefined macro: AC_CHECK_PROGS
autoreconf: /usr/bin/autoconf failed with exit status: 1
`
