### ISSUE TITLE
[Qt Applet] Don't jump the accept/block dialog around

### ISSUE THREAD

**Issue by genodeftest** [USBGuard/usbguard#152]
Currently, when attaching a new USB device, the user is prompted by a dialog to accept or block the new device. This device is being displayed at different screen positions on successive tries. I think I read that this is a "security" feature, but it isn't: In case the attacker has access to the mouse or cursor, he will also have access to the physical or virtual keyboard, rendering this "defense" mechanism unusable.

**Comment by genodeftest** [comment]
This is now configurable, as in "Randomize position of the window".

I'll leave this issue open because I still think this feature should be removed. It is __not__ a security feature!

**Comment by BenjaminSchubert** [comment]
I agree with @genodeftest this brings a false sense of security.

@dkopecek should I remove this in #178 ?

**Comment by dkopecek** [comment]
> @dkopecek should I remove this in #178 ?

Yes, thanks!

**Comment by vk5tu** [comment]
It's insecure in a common use-case. My authorise dialog was displayed in front of a few hundred people because it chose to display on the projector screen rather than then laptop screen.

**Comment by genodeftest** [comment]
@vk5tu :
> It's insecure in a common use-case. My authorise dialog was displayed in front of a few hundred people because it chose to display on the projector screen rather than then laptop screen.

This is a separate issue and I guess you should file a separate bug report for that.
