### ISSUE TITLE
DMA/IOMMU Monitor

### ISSUE THREAD

**Issue by zaolin** [USBGuard/usbguard#177]
Hey,

Google implemented a IOMMU/DMA monitor. Details gonna be released soon. Maybe also interesting ;)
https://cloudplatform.googleblog.com/2017/02/fuzzing-PCI-Express-security-in-plaintext.html

**Comment by tammar96** [comment]
Is there any new information about that project?

**Comment by zaolin** [comment]
I guess it is not released yet :-/
