### ISSUE TITLE
tar.gz release is not complete

### ISSUE THREAD

**Issue by murinicanor** [USBGuard/usbguard#215]
hi,

the tar.gz release archive does not contain all the files- i stumbled upon that when looking for the zsh completion files. the .tar.gz only contains the `bash_completion` folder in `scripts`

cheers,
muri

**Comment by murinicanor** [comment]
oh, i just saw that there are two different .tar.gz's on the github release page, one of them is complete and the other one is not

**Comment by Arvedui** [comment]
Yes, but unfortunately it is the signed one, that is not complete.
