### ISSUE TITLE
USBGuard daemon seems to leak filehandles

### ISSUE THREAD

**Issue by murinicanor** [USBGuard/usbguard#219]
From the debian BTS (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887671)

> After uptime of 15 days of my desktop Debian testing system, I ran into the
> problem that usbguard commandline utility was refusing to connect to the
> daemon. From "journalctl | grep usbguard" I saw the following:
> 
> Jan 16 13:38:39 nmos6502 usbguard-daemon[603]: [1516102719.737] (W) USB Device
> Exception: SysFSDevice: uevent: Too many open files
> Jan 16 13:38:39 nmos6502 usbguard-daemon[603]: [1516102719.737] (W)
> SysFSDevice: uevent: Too many open files
> 
> .. repeating many times. After restarting usbguard daemon via "systemctl
> restart usbguard" things returned to normal, but I decided to examine further.
> Turns out that each USB device attach/reattach sequence causes usbguard-daemon
> to leave 8 new file descriptors open:
> 
> [root@nmos6502 ~]# pidof usbguard-daemon
> 14319
> [root@nmos6502 ~]# ls /proc/14319/fd | wc -l
> 192
> [root@nmos6502 ~]# ls /proc/14319/fd | wc -l
> 201
> 
> This can be easily reproduced on my system by attaching and removing any USB
> device repeatedly.

i've reproduced the behaviour with 0.7.1

**Comment by dkopecek** [comment]
Thanks for the report, I'll look into this ASAP.
