### ISSUE TITLE
No IPC connection with non-local user database

### ISSUE THREAD

**Issue by AHeinlein** [USBGuard/usbguard#223]
Hello,
I have an issue using usbguard in a networked environment with users and groups stored in LDAP (using libnss-ldapd on Debian). I have "IPCAllowedGroups=root users" in usbguard-daemon.conf.
'users' is a group stored in LDAP, and 'myuser' is a user stored in LDAP and a member of 'users'.
When 'myuser' logs in and starts the applet, it cannot make an IPC connection. When I issue 'sudo systemctl restart usbguard', IPC connection works.
So it seems to me that the list of users and groups is only read once at startup, and that the LDAP user database is not ready at that time. I tried inserting:
```
After=nss-user-lookup.target
Wants=nss-user-lookup.target
```
into the systemd unit file of usbguard, but that doesn't work.

Do you have any idea how to solve this?

**Comment by radosroka** [comment]
Can you provide a debug log and id command output?
