### ISSUE TITLE
Many releases are marked as 'pre-release'

### ISSUE THREAD

**Issue by mboelen** [USBGuard/usbguard#232]
I [reviewed USBGuard](https://linuxsecurity.expert/tools/usbguard/) for our security tools section, and saw that most releases on GitHub are not 'finished'. They are marked as pre-release, resulting in the last release being very outdated.

Is there a reason for that or can the last release be marked as a 'release'?

**Comment by dkopecek** [comment]
Yes, all releases so far are pre-release. 1.0.0 should be the first one not marked as such.
