### ISSUE TITLE
Segfault happened at 

### ISSUE THREAD

**Issue by kisst** [USBGuard/usbguard#234]
Hi Guys,

My USBguard is keep crashing at random times, and more often around when I put the laptop to sleep, the error and the env bellow.

About me env:
 - OS: Ubuntu 17.10
 - Kernel: 4.13.0-39-generic
 - usbguard-version: 0.7.0+ds1-2

Title
```
usbguard-applet-crashed with SIGSEGV in QWindow::handle()
```
SegAnalysis
```
Segault happened at: 0x7f01bbf2a2c0 <_ZNK7QWindow6handleEv>:  mov 0x8(%rdi),%rax
PC "0x8(%rdi)" (0x00000008) not located in a known VMA region ( needed readable region)!
destanation "%rax" ok
```
SegReason
```
reading NULL VMA
```

**Comment by dkopecek** [comment]
Closing this as I've removed the applet from the main usbguard repository in https://github.com/USBGuard/usbguard/commit/bf3bb09edf491892617d35b55edec06f92d2743f. The plan is to simplify it down to a minimal required use case and maintain it in a separate repository.
