### ISSUE TITLE
is it possible to skip the asciidoctor requirement if we don't want documentation?

### ISSUE THREAD

**Issue by thebunnyrules** [USBGuard/usbguard#237]
Hi, I'm just trying out usbguard and I want to compile it. I don't need the manpages for now and asciidoctor isn't on my distro and I don't want to build just to try usbguard. Is there a configure switch to skip the asciidoc step?

**Comment by dkopecek** [comment]
Hi, I think PR #236 solves your problem. I'm going to merge it once I'm done with the review and I'm going to make a new release in a couple of days.

**Comment by dkopecek** [comment]
Hi, I've merged the PR and also changed the man page generation process to use asciidoc (a2x) instead of asciidoctor. I hope that helps for your use case.
