### ISSUE TITLE
with-interface equals-ordered doesn't seem to work as intended.

### ISSUE THREAD

**Issue by Allen-Webb** [USBGuard/usbguard#247]
I wrote the following regression test to verify this and unless I am misunderstanding the equals-ordered operator is it is broken. The following test fails:

#include "usbguard/Rule.hpp"

#include <catch.hpp>

using namespace usbguard;

TEST_CASE("Regression: GitHub issue #247", "[regression]")
{
  Rule target_rule;
  Rule source_rule;
  const std::string source_rule_spec = \
      "allow with-interface equals-ordered { 03:00:00 03:01:01 }";
  const std::string target_rule_spec = \
      "allow with-interface equals-ordered { 03:00:00 03:01:01 }";
  CHECK_NOTHROW(target_rule = Rule::fromString(target_rule_spec));
  CHECK_NOTHROW(source_rule = Rule::fromString(source_rule_spec));
  REQUIRE(source_rule.appliesTo(target_rule));
}

**Comment by dkopecek** [comment]
Thanks! Looks like a bug. I'll look into it.

**Comment by dkopecek** [comment]
Turned out to be a wrong return value in the operator implementation:
https://github.com/USBGuard/usbguard/commit/ccb7046082ad801fee056a784f41c71883c806b2#diff-f0aba824e0617fced2c9c026ffcd15b1L416
