### ISSUE TITLE
IPC getParameter and setParameter only for InsertedDevicePolicy

### ISSUE THREAD

**Issue by RyuzakiKK** [USBGuard/usbguard#255]
I noticed that the IPC/DBus command getParameter and setParameter works just for the value InsertedDevicePolicy. All the others are not configurable.

https://github.com/USBGuard/usbguard/blob/414658044b90b2111001cf5763cbd7639f4253d6/src/Daemon/Daemon.cpp#L631

Would you accept a PR that adds the remaining configuration options? In particular I'm interested in being able to get and set the ImplicitPolicyTarget.

**Comment by muelli** [comment]
FTR: https://github.com/USBGuard/usbguard/pull/265

**Comment by muelli** [comment]
so this can be closed I guess, given that the PR mentioned above has been merged..

**Comment by RyuzakiKK** [comment]
Right, this is done.
