### ISSUE TITLE
Debian 9 amd64 terminate called without an active exception

### ISSUE THREAD

**Issue by rgmalagon** [USBGuard/usbguard#288]

**Comment by tweksteen** [comment]
Could you please provide more details on this issue? How did you trigger this message? Which version of USBGuard are you using? Could you share your `usbguard-daemon.conf`?

**Comment by rgmalagon** [comment]
When install from debian 9 official repository usbguard 0.6.2 amd64, can not execute program, always show terminate called without an active exception.
usbguard-daemon.conf
//------------------------
RuleFile=/usr/local/etc/usbguard/rules.conf
ImplicitPolicyTarget=block
PresentDevicePolicy=keep
PresentControllerPolicy=keep
IPCAllowedUsers=root
IPCAllowedGroups=wheel
DeviceRulesWithPort=false
//--------------------------

**Comment by rgmalagon** [comment]
i fix the problem compiling from source code to 32 bit architecture and add  i386 architecture to amd64 system. 
I think it's a compatibility problem with 64 bit libraries, because the 32 bit version is working
