### ISSUE TITLE
USBGuard in Mac?

### ISSUE THREAD

**Issue by Henrietta1989** [USBGuard/usbguard#296]
Does your instructions in compilation page work in Mac Mojave?

https://usbguard.github.io/documentation/compilation.html

**Comment by muelli** [comment]
I don't see how it could possibly work on a Mac. USBGuard uses functionality of Linux (the kernel). The Mac would need to have equivalent switches.

**Comment by radosroka** [comment]
As far as I know the Mac USB kernel subsystem does not contain these security features like Linux does if any. Therefore it is not possible to run USBGuard on Mac.
