### ISSUE TITLE
Can't use yubikey serial

### ISSUE THREAD

**Issue by qmemcpy** [USBGuard/usbguard#332]
So I have a problem with USBGuard.

In the docs (usbguard-rules.conf(5) manual page), you use an example where you can see a Yubikey's serial key (allow 1050:0011 name "Yubico Yubikey II" serial "0001234567") as it'd be shown with the softwares provided by Yubico.

I've been trying to create rules using my own serial so that only my keys would be allowed on my PC, however it seems USBGuard just can't pick up the serial...

```
 $ ~ sudo usbguard generate-policy -PX | grep Yubikey
allow id 1050:0407 serial "" name "Yubikey 4 OTP+U2F+CCID" with-interface { 03:01:01 03:00:00 0b:00:00 }
```

This is a bit annoying as I can't do what I'd like to do.
Of course I can still create a Yubikey rule but that rule will allow any and every Yubikey that match my model to be plugged in.
I also tried using the hash calculated by USBGuard but the hash end up being the same for all the Yubikeys I plug in (Again, same model, I'm sure it wouldn't match if the model was different but that's not the point).

Is that normal? Is it a bug in my system somewhere?
I'm using the latest version of USBGuard on a fully updated Arch Linux (Default kernel), if that helps...

Thanks in advance

**Comment by tweksteen** [comment]
It is up to the device manufacturer to include or not a serial number. In this case, I believe Yubico did not add a serial to your device. You can double check what is found by the kernel, either via lsusb or sysfs:

```
# USB device with no serial
tweek@sys/bus/usb/devices/2-5.1.1$ cat manufacturer 
Yubico
tweek@/sys/bus/usb/devices/2-5.1.1$ cat serial
cat: serial: No such file or directory

# Different USB device that has a non-null serial
tweek@:/sys/bus/usb/devices/2-13$ cat idVendor 
0451
tweek@:/sys/bus/usb/devices/2-13$ cat serial 
D00540595BFB
```

If that device does not expose this value, there is nothing usbguard can do about it. I'm closing this for now. If you want to re-open, please include the ouput of `lsusb -vvv` proving that the device has a valid serial. Thanks.
