### ISSUE TITLE
Allow device temporary

### ISSUE THREAD

**Issue by fakhamatia** [USBGuard/usbguard#338]
Please add an option to add devices temporary.
Devie is allowed until reboot or 10 times connect and disconnect.

**Comment by muelli** [comment]
Temporary (or volatile) rules exist. Does that do what you need?

A counter sounds complicated. What is your usecase for that?

**Comment by fakhamatia** [comment]
I want to add a USB flash temporary for just a copy, and then block that after reboot or disconnect. How can I do this?

**Comment by muelli** [comment]
Either `usbguard allow-device` or `usbguard append-rule` should do what you want.
