### ISSUE TITLE
Details about "with-connect-type"

### ISSUE THREAD

**Issue by jean-christophe-manciot** [USBGuard/usbguard#340]
@dkopecek
Ubuntu 20.04
usbguard 0.7.5+ds-1

I have noticed a relatively new parameter ```with-connect-type``` in /etc/usbguard/rules.conf.
The [documentation](https://github.com/USBGuard/usbguard/blob/master/doc/man/usbguard-rules.conf.5.adoc) is not very verbose about it.
- What are all the possible types, meanings and effects of ```connect-type```?
- if that parameter is omitted, does that just mean that the rule is less stringent as with other parameters, or is there other side effects?

**Comment by tammar96** [comment]
Hello, I will make a PR in next days to enhance the docs.
Here is what I found in commits:

> Add with-connect-type rule attribute to filter and control devices through the portX/connect_type flag. This flag is getting more commonly setup and is useful, for instance, to distinguish between internal ("hardwired") and external ("hotplug") ports.
