### ISSUE TITLE
Can't allow usbguard device permanently

### ISSUE THREAD

**Issue by ibahnasy** [USBGuard/usbguard#347]
Unable to whitelist device permanently due to filesystem restriction in the systemd unit file.
If "ReadOnlyPaths=-/" is disabled, it works fine

Package version(s): 0.7.5-1

Steps to reproduce:
```
# usbguard allow-device 15 -p
IPC ERROR: request id=1: FileRuleSet saving: /etc/usbguard/rules.conf: Read-only file system
```

**Comment by c0d3z3r0** [comment]
I had the same problem; workaround:

~~~
sudo mkdir /etc/systemd/system/usbguard.service.d
cat <<"EOF" | sudo tee /etc/systemd/system/usbguard.service.d/override.conf
[Service]
ReadWritePaths=-/dev/shm -/var/log/usbguard -/tmp -/etc/usbguard
EOF
~~~

**Comment by radosroka** [comment]
Fixed in : https://github.com/USBGuard/usbguard/commit/fffd3d3fc16ff3426e95350b061a44f0ce02d3c7
