### ISSUE TITLE
Only prereleases available

### ISSUE THREAD

**Issue by legendofa** [USBGuard/usbguard#373]
I am asking due to the inclusion in solus, will there be a release in the future?

https://dev.getsol.us/T8069

**Comment by radosroka** [comment]
> I am asking due to the inclusion in solus, will there be a release in the future?
> 
> https://dev.getsol.us/T8069

Hi,

yes we are going to switch to proper releases for sure. The only thing left is an  API stabilization so we can safely use .so versioning.
