### ISSUE TITLE
Installing on Fedora CoreOS 31 - Conflict with setroubleshoot.

### ISSUE THREAD

**Issue by medined** [USBGuard/usbguard#388]
I don't know if there is anything to be done but in case there is I wanted to report the issue. This is the error message. I don't know which package is using the newer version.

```
Forbidden base package replacements:
  libreport-filesystem 2.12.0-1.fc31 -> 2.13.1-3.fc31 (updates)
```

**Comment by genodeftest** [comment]
I'd rather report this to Fedora's downstream ([bugzilla link](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=usbguard&list_id=11158268&product=Fedora&product=Fedora%20EPEL)). This looks like a packaging issue to me.

**Comment by medined** [comment]
I agree.
