### ISSUE TITLE
usbguard 0.7.6 and later crashes on openSUSE 15.2 when started through systemd

### ISSUE THREAD

**Issue by lemmy04** [USBGuard/usbguard#392]
openSUSE Leap 15.2 comes with usbguard 0.7.6, and uses the .service file that comes with usbguard... and on Leap 15.2 usbguard-daemon crashes when started through that. One of the many restrictive settings in the .service file might not be compatible with Leap 15.2.

**Comment by lemmy04** [comment]
See https://bugzilla.opensuse.org/show_bug.cgi?id=1173750

**Comment by mgerstner** [comment]
The problems comes from `SystemCallFilter=@system-service` which seems not to be supported on older systemd versions. Then no system calls at all are allowed and the daemon crashes during execution of the first systemcall with SIGSYS. The warning in the journal is as follows:

```
/usr/lib/systemd/system/usbguard.service:30: Don't know system call group, ignoring: @system-service
```

**Comment by radosroka** [comment]
Well, these are packagers issues. They should patch it.
