### ISSUE TITLE
Misunderstanding on operators explanation

### ISSUE THREAD

**Issue by Ilya87** [USBGuard/usbguard#395]
Part from the documentation for usbguard-rules.conf

Operator **all-of**:
The device attribute set must contain **all of the specified** values for the rule to match.

Operator **equals**:
The device attribute set must contain **exactly the same set** of values for the rule to match.

If I understand English language right  **all of the specified** is equal to **exactly the same set** because **all** of the specified _is_ the set.

Or the meaning of equals operator should be: The device attribute set must contain **only specified set** of values for the rule to match.

**Comment by radosroka** [comment]
> Part from the documentation for usbguard-rules.conf
> 
> Operator **all-of**:
> The device attribute set must contain **all of the specified** values for the rule to match.
> 
> Operator **equals**:
> The device attribute set must contain **exactly the same set** of values for the rule to match.
> 
> If I understand English language right **all of the specified** is equal to **exactly the same set** because **all** of the specified _is_ the set.
> 
> Or the meaning of equals operator should be: The device attribute set must contain **only specified set** of values for the rule to match.

**all-of** is kind of superset of **equals** because **all-of** matches also larger set where **equals** checks for the size equality first.
