### ISSUE TITLE
Polkit policy is not valid with newest versions of Polkit

### ISSUE THREAD

**Issue by LucasParsy** [USBGuard/usbguard#403]
With new versions of Polkit, the value `auth_self_keep_session` is no more valid for the tags `<allow_any>`, `<allow_inactive>` and `<allow_active>`.
The [usbguard policy config](https://github.com/USBGuard/usbguard/blob/master/src/DBus/org.usbguard1.policy) is not parsed anymore by new versions of Polkit, and the defined actions are unavailable.

#### proposed solutions

*  `auth_self_keep_session`: allowed executing an action after authenticating, and the redo the action without auth for all the rest of the session.
 It is now unavailable

* `auth_self_keep`: the authorization is kept for a brief period (e.g. five minutes).
It is most probably not retro-compatible. (I found no reference online of `auth_self_keep` on pages mentioning `auth_self_keep_session`)

* `auth_self`: You have to re-authenticate at each call of the action.
 This argument is retro-compatible.

Should we replace occurrences of `auth_self_keep_session` with `auth_self_keep` or `auth_self`?

**Comment by hartwork** [comment]
I confirm for polkit version 0.120:
```console
# sudo /usr/lib/polkit-1/polkitd --replace 
[..]
** (polkitd:12385): WARNING **: 01:10:03.007: Unknown PolkitImplicitAuthorization string 'auth_self_keep_session'

** (polkitd:12385): WARNING **: 01:10:03.007: Error parsing file with URI 'file:///usr/share/polkit-1/actions/org.usbguard1.policy': 14: parse error: parsing aborted
```
