### ISSUE TITLE
How to create rule contains filesystem?

### ISSUE THREAD

**Issue by ksiezna** [USBGuard/usbguard#408]
Hi, how to create rule to allow device with specified filesystem, e.g. xfs? This information is unable to find in documentation.
Regards.

**Comment by muelli** [comment]
AFAIU, this appears to be pretty much out of scope.

**Comment by ksiezna** [comment]
Out of USBGuard scope?

**Comment by ksiezna** [comment]
Out of USBGuard scope?

**Comment by ZoltanFridrich** [comment]
Afaik USB descriptors don't contain information about the filesystem present on the device. USBGuard works with information found in USB descriptors. Imo this is out of USBGuard scope.

**Comment by muelli** [comment]
> Afaik USB descriptors don't contain information about the filesystem present on the device.

correct.
Close this bug.
