### ISSUE TITLE
musl libc compatibility 

### ISSUE THREAD

**Issue by mpolanski** [USBGuard/usbguard#423]
I tried to use USBGuard on Alpine Linux, but I doesn't work on musl-based distributions. I successfully built it using a patch provided by Void Linux: https://github.com/void-linux/void-packages/blob/427d50c6a66e4a1338dbe230a41b98a2419116a9/srcpkgs/usbguard/patches/musl.patch, but it's not enough. At startup USBGuard tries to parse /etc/nsswitch.conf file, which is present only on glibc systems.

**Comment by radosroka** [comment]
I believe you can add this file. It just needs to be there even empty... You can install nsswitch.conf by usbguard package.

**Comment by radosroka** [comment]
It should be easy to patch usbguard so the file won't be necessary.

**Comment by radosroka** [comment]
Try this patch: https://github.com/USBGuard/usbguard/commit/b1b1f4bed9507d3c547d174f67be9e3a9c2e5d99

**Comment by mpolanski** [comment]
Thanks for preparing the patch. Works as expected.

**Comment by mpolanski** [comment]
USBGuard is now available on Alpine Linux (in the testing repository): https://pkgs.alpinelinux.org/packages?name=usbguard&branch=edge

**Comment by radosroka** [comment]
Thank you!
