### ISSUE TITLE
Block vs Reject

### ISSUE THREAD

**Issue by molitona** [USBGuard/usbguard#473]
Hi, I wonder what's the deep difference between Block and Reject (I've already seen the doc hint)
![g](https://user-images.githubusercontent.com/35532337/114932662-aabb8680-9e2f-11eb-9734-8da835f8cf16.png)

And, 
Do they both prevent USBKiller ?
Do they both prevent the other malicious USB's (those who exfiltrate data) ?

**Comment by Cropi** [comment]
Hi @molitona,

The key difference is that:
-  ```block``` will deauthorize the device and it will stay in a blocked state until it is authorized.
- ```reject``` will deauthorize **and remove** the device. In case you would like to use a rejected device again, you will have to reinsert it.

Both should protect against malicious USBs by a set of usbguard rules.

**Comment by muelli** [comment]
But USBKiller is the name of a device that has too high voltage for USB, no? In that case, any software based solution is not capable of defending against such an attack.

**Comment by molitona** [comment]
Oh, unfortunately. Thanks!

-------- Original Message --------

**Comment by molitona** [comment]
Then, usbguard can only protect software attacks (those who exfiltrate data), right ?

-------- Original Message --------

**Comment by Cropi** [comment]
USBGuard was designed to authorize/deauthorize/reject usb devices by a set of rules. It's up to the user to decide, which devices are authorized for use. To sum up, deauthorized devices can not exfiltrate data from your machine.

**Comment by molitona** [comment]
Ok, thanks!

-------- Original Message --------
