### ISSUE TITLE
usbguard-applet-qt missing in Debian Testing (bullseye)

### ISSUE THREAD

**Issue by AreYouLoco** [USBGuard/usbguard#476]
What happened to the nice gui of usbguard? I've read somewhere that it was merged into usbguard but cannot install/compile it for Debian Bullseye. What happened?

**Comment by AreYouLoco** [comment]
I see that in latest source there is missing --with-gui-qt=qt5 option that prevents from building applet.

**Comment by genodeftest** [comment]
It has been removed from usbguard 0.7.5, see the [release notes](https://github.com/USBGuard/usbguard/releases/tag/usbguard-0.7.5) and it will not come back.

According to the [official announcement](https://usbguard.github.io/blog/2019/usbguard-0.7.6) you should use [usbguard-notifier](https://github.com/Cropi/usbguard-notifier) now. There is also some very basic integration in GNOME 40.

**Comment by MatejKovacic** [comment]
Are there any plans for integration of `usbguard-notifier` applet into the `usbguard`? It would be nice if people would be able to use GUI... I am sure there will be much more users for that great software.

**Comment by hartwork** [comment]
Based on https://github.com/USBGuard/usbguard/issues/476#issuecomment-853766678 I believe this ticket can be closed as "wont fix".
