### ISSUE TITLE
Git repository contains 7 merged branches — can they be deleted?

### ISSUE THREAD

**Issue by hartwork** [USBGuard/usbguard#520]
Hi!

Using [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) I have identified 7 branches that have been fully merged to `master` by now:

Regular merges / fast-forwards (3x):
- [`coverity_scan`](https://github.com/USBGuard/usbguard/commits/coverity_scan)
- [`fix-build-issue`](https://github.com/USBGuard/usbguard/commits/fix-build-issue)
- [`fix-build-issue-2`](https://github.com/USBGuard/usbguard/commits/fix-build-issue-2)

De-facto merges i.e. completely cherry-picked (4x):
- [`missingfolder`](https://github.com/USBGuard/usbguard/commits/missingfolder)
- [`remove-wired`](https://github.com/USBGuard/usbguard/commits/remove-wired)
- [`setup-github-actions`](https://github.com/USBGuard/usbguard/commits/setup-github-actions)
- [`travis`](https://github.com/USBGuard/usbguard/commits/travis)

Can someone with permissions confirm and delete them?  Are they still needed?

Best, Sebastian

**Comment by radosroka** [comment]
I've removed them.
