### ISSUE TITLE
Please merge release commit

### ISSUE THREAD

**Issue by b1rger** [USBGuard/usbguard#553]
The github page of the release commit https://github.com/USBGuard/usbguard/commit/a9380ddee2abfc9318080774aad001889f01839a says:
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

not sure how that happened, but it would be great if that commit got merged ;)

**Comment by hartwork** [comment]
@b1rger I confirm, thanks for the report. @radosroka it's not too late to fast-forward master to Git tag `usbguard-1.1.2`. Do you have a minute?

**Comment by radosroka** [comment]
Oh no. It seems that my release commit was not pushed somehow... Now it is fixed.
