### ISSUE TITLE
Add option --version

### ISSUE THREAD

**Issue by jk-10** [USBGuard/usbguard#570]
Running `usbguard --version` at least on Ubuntu 22.04 does not produce any versioning information. Handling these issues and fixes might be easier with known version numbers.

So please add support for new option `--version`

**Comment by hartwork** [comment]
@jk-10 I second that there should be `--version` supported by at least command `usbguard`. :+1: 

Just for your information, one way to check which version of USBGuard (or any distro package) you have installed on Ubuntu (and Debian) is `apt-cache policy usbguard`, e.g.:
```console
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# apt-cache policy usbguard
usbguard:
  Installed: 1.1.2+ds-3+b1
  Candidate: 1.1.2+ds-3+b1
  Version table:
 *** 1.1.2+ds-3+b1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by Cropi** [comment]
I agree that this could come in handy when debugging future issues.
