### ISSUE TITLE
Partially block device by interface

### ISSUE THREAD

**Issue by tuxArg** [USBGuard/usbguard#595]
Hi, I wonder if it's possible to block some (but not all) the interfaces of a USB device.
For example, if I have a USB flash storage (08:*:*) that also has (or ask for, I don't know the actual term) 03:*:* interface, to let it be a flash storage but not something else.

Thanks

**Comment by muelli** [comment]
No: #67 

Patches welcome!

**Comment by radosroka** [comment]
I'll close this as duplicate of #67.
