### ISSUE TITLE
Monitoring copied file to a usb key 

### ISSUE THREAD

**Issue by p1r4t3-s4il0r** [USBGuard/usbguard#607]
Hello, 

I'm using USB guard to prevent users from connecting an untrusted device to their machines (Unix). 

Once the device is trust, I would like to keep logs of which file is copied to a USB key. I would like to have :
 - the username
 - the timestamp
 - the file name
 - an the most important for me : the hash of the file.

I didn't find any docs about this with USB guard, is it doable ? And, if not, what tool can I use to do so ?

Today, I have to go on each machine to authorize a device. I would like to "centralize" the authorizations. I would like to authorize devices regarding the connected user using his LDAP account. Is there any trick for this ? And should I open an other issue ?

Thanks.

**Comment by radosroka** [comment]
Perhaps (just a wild guess) https://github.com/linux-audit can do something like that.

**Comment by p1r4t3-s4il0r** [comment]
It seems a bit overkill
But I'll give it a try and let you know

**Comment by radosroka** [comment]
If you don't mind I will close the issue. Feel free to reopen if needed.
