### ISSUE TITLE
Implement IPC authentication

### ISSUE THREAD

**Issue by dkopecek** [USBGuard/usbguard#8]
The idea is to use PKI for IPC authentication where the user authenticates itself using IPC message signing. Allowing a user/app to use the IPC would require to register a public key with the daemon.

**Comment by genodeftest** [comment]
Why not simply use polkit?

**Comment by dkopecek** [comment]
This was about the usbguard-daemon native IPC. Polkit can be (or rather should be) integrated in usbguard-dbus.
